title: Data Augmentation and Curation in Medical Imaging Workshop
show_downloads: true
theme: jekyll-theme-cayman

# Layout
show_social: true
show_excerpts: false
show_sidebar: true

# Menu
navigation:
  - {file: "index.html", title: "Home", icon: home}
  - {file: "people.md", title: "People", icon: address-card}
  - {file: "/program.md", title: "Program", icon: address-card}

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-archives
  - jekyll-seo-tag